"""
Webster Alpha

Conversation Manager
"""

from __future__ import annotations

from core.conversation.context import ConversationContext
from core.conversation.session import ConversationSession
from core.events.event import Event
from core.events.event_bus import EventBus
from core.events.event_types import EventType
from core.memory.manager import MemoryManager
from core.messaging.message import Message


class ConversationManager:
    """
    Coordinates Webster conversation sessions.
    """

    def __init__(
        self,
        memory: MemoryManager,
        event_bus: EventBus | None = None,
    ) -> None:

        if memory is None:

            raise ValueError(
                "ConversationManager requires a MemoryManager."
            )

        self._memory = memory
        self._event_bus = event_bus
        self._session: ConversationSession | None = None
        self._initialized = False

    # =====================================================
    # Lifecycle
    # =====================================================

    def initialize(
        self,
    ) -> None:
        """Initialize the conversation subsystem."""

        if self._initialized:

            return

        if self._memory is None:

            raise RuntimeError(
                "ConversationManager requires a MemoryManager."
            )

        if hasattr(self._memory, "initialized"):

            if not self._memory.initialized:

                self._memory.initialize()

        self._initialized = True

    # -----------------------------------------------------

    def shutdown(
        self,
    ) -> None:
        """Stop the conversation subsystem without deleting history."""

        if not self._initialized:

            return

        self._initialized = False

    # -----------------------------------------------------

    def start(
        self,
    ) -> ConversationSession:
        """Start or return the active conversation session."""

        if not self._initialized:

            self.initialize()

        if self._session is None:

            self._session = ConversationSession()
            self._session.activate()

        elif not self._session.active:

            self._session.activate()

        return self._session

    # =====================================================
    # State
    # =====================================================

    @property
    def initialized(
        self,
    ) -> bool:

        return self._initialized

    @property
    def ready(
        self,
    ) -> bool:

        return (
            self._initialized
            and self._memory is not None
        )

    @property
    def session(
        self,
    ) -> ConversationSession | None:

        return self._session

    @property
    def context(
        self,
    ) -> ConversationContext:

        return self.build_context()

    # =====================================================
    # Messages
    # =====================================================

    def receive(
        self,
        message: Message,
    ) -> None:
        """Receive and store an internal Webster message."""

        if not isinstance(message, Message):

            raise TypeError(
                "ConversationManager.receive expects a Message."
            )

        session = self.start()

        session.add_message(
            message
        )

        if self._event_bus is not None:

            self._event_bus.publish(
                Event(
                    name=EventType.CONVERSATION_UPDATED.name,
                    source="conversation_manager",
                    data={
                        "sender": message.sender,
                        "receiver": message.receiver,
                        "payload": message.payload,
                    },
                )
            )

    # -----------------------------------------------------

    def add_user_message(
        self,
        content: str,
    ) -> None:
        """Add a message originating from the user."""

        content = str(content).strip()

        if not content:

            raise ValueError(
                "User message cannot be empty."
            )

        self.receive(
            Message(
                sender="user",
                receiver="webster",
                payload=content,
                message_type="user",
            )
        )

    # -----------------------------------------------------

    def add_assistant_message(
        self,
        content: str,
    ) -> None:
        """Add a message generated by Webster."""

        content = str(content).strip()

        if not content:

            raise ValueError(
                "Assistant message cannot be empty."
            )

        self.receive(
            Message(
                sender="webster",
                receiver="user",
                payload=content,
                message_type="assistant",
            )
        )

    # =====================================================
    # Context
    # =====================================================

    def build_context(
        self,
    ) -> ConversationContext:
        """Build context from the recent active conversation."""

        context = ConversationContext()

        if self._session is None:

            return context

        for message in self._session.messages[-10:]:

            context.add_message(
                message
            )

        if self._event_bus is not None:

            self._event_bus.publish(
                Event(
                    name=EventType.CONVERSATION_UPDATED.name,
                    source="conversation_manager",
                    data={
                        "message_count": self._session.message_count,
                    },
                )
            )

        return context

    # =====================================================
    # Session Control
    # =====================================================

    def finish(
        self,
    ) -> None:

        if self._session is not None:

            self._session.finish()

    def clear(
        self,
    ) -> None:

        self._session = None

    # =====================================================
    # Health
    # =====================================================

    def health(
        self,
    ) -> dict:

        message_count = 0

        if self._session is not None:

            message_count = self._session.message_count

        return {
            "initialized": self._initialized,
            "healthy": self.ready,
            "ready": self.ready,
            "messages": message_count,
            "memory_available": self._memory is not None,
            "session_active": (
                self._session.active
                if self._session is not None
                else False
            ),
        }

    # =====================================================
    # Representation
    # =====================================================

    def __repr__(
        self,
    ) -> str:

        state = "active" if (
            self._session is not None
            and self._session.active
        ) else "idle"

        return (
            "ConversationManager("
            f"{state}"
            ")"
        )
