"""
Webster Alpha

Conversation Manager
"""

from __future__ import annotations

from core.conversation.context import ConversationContext
from core.conversation.history import ConversationHistory
from core.conversation.session import ConversationSession
from core.events.event_bus import EventBus
from core.events.event import Event
from core.events.event_types import EventType
from core.memory.manager import MemoryManager
from core.messaging.message import Message


class ConversationManager:
    """
    Coordinates conversation sessions.
    """

    def __init__(
        self,
        memory: MemoryManager,
        event_bus: EventBus | None = None,
    ) -> None:

        self._memory = memory

        self._event_bus = event_bus

        self._session: ConversationSession | None = None

        self._initialized = False

    # =====================================================
    # Lifecycle
    # =====================================================

    def initialize(
        self,
    ) -> None:
        """
        Initialize the conversation subsystem.

        The conversation manager depends on the memory
        manager being available before it becomes ready.
        """

        if self._initialized is False:

            return

        if self._memory is None:

            raise RuntimeError(

                "ConversationManager requires "
                "a MemoryManager."

            )

        #
        # Initialize the dependency if necessary.
        #

        if hasattr(
            self._memory,
            "initialized",
        ):

            if not self._memory.initialized:

                self._memory.initialize()

        #
        # Conversation state is already stored in memory.
        # No external resource needs to be opened here.
        #

        if self._messages is None:

            self._messages = []

        self._initialized = True

    # -----------------------------------------------------

    def shutdown(
        self,
    ) -> None:
        """
        Shutdown the conversation subsystem.

        Conversation history is deliberately preserved.
        """

        if not self._initialized:

            return

        self._initialized = False

    # =====================================================
    # State
    # =====================================================

    @property
    def initialized(
        self,
    ) -> bool:

        return self._initialized

    # -----------------------------------------------------

    @property
    def ready(
        self,
    ) -> bool:

        return (

            self._initialized

            and self._memory is not None

        )

    # =====================================================
    # Health
    # =====================================================

    def health(
        self,
    ) -> dict:
        """
        Return conversation subsystem health.
        """

        return {

            "initialized": self._initialized,

            "healthy": self.ready,

            "ready": self.ready,

            "messages": len(
                self._messages
            ),

            "memory_available": (
                self._memory is not None
            ),

        }

    #
    # ---------------------------------------------------------
    # Messages
    # ---------------------------------------------------------
    #

    def receive(
        self,
        message: Message
    ) -> None:

        if self._session is None:

            self.start()

        self._session.history.append(
            message
        )

        if self._event_bus is not None:
            self._event_bus.publish(
                Event(
                    name=EventType.CONVERSATION_UPDATED.name,
                    source="conversation_manager",
                    data={
                        "sender": message.sender,
                        "receiver": message.receiver,
                        "payload": message.payload,
                    },
                )
            )

    # =====================================================
    # Application Message API
    # =====================================================

    def add_user_message(
        self,
        content: str,
    ) -> None:
        """
        Add a message originating from the user.

        This is the application-facing wrapper around
        the internal receive(Message) API.
        """

        if not content:

            raise ValueError(
                "User message cannot be empty."
            )

        message = Message(

            sender="user",

            receiver="webster",

            payload=content,

            message_type="user",

        )

        self.receive(
            message
        )

    # -----------------------------------------------------

    def add_assistant_message(
        self,
        content: str,
    ) -> None:
        """
        Add a message generated by Webster.
        """

        if not content:

            raise ValueError(
                "Assistant message cannot be empty."
            )

        message = Message(

            sender="webster",

            receiver="user",

            payload=content,

            message_type="assistant",

        )

        self.receive(
            message
        )

    #
    # ---------------------------------------------------------
    # Context
    # ---------------------------------------------------------
    #

    def build_context(
        self
    ) -> ConversationContext:

        context = ConversationContext()

        if self._session is None:

            return context

        #
        # Recent messages
        #

        for message in self._session.history.last(10):

            context.add_message(
                message
            )

        if self._event_bus is not None:
            self._event_bus.publish(
                Event(
                    name=EventType.CONVERSATION_UPDATED.name,
                    source="conversation_manager",
                    data={
                        "message_count": self._session.history.count,
                    },
                )
            )

        #
        # Memory retrieval
        # (implemented later)
        #

        return context

    #
    # ---------------------------------------------------------
    # Lifecycle
    # ---------------------------------------------------------
    #

    def finish(
        self
    ) -> None:

        if self._session:

            self._session.finish()

    def clear(
        self
    ) -> None:

        self._session = None

    #
    # ---------------------------------------------------------
    # Representation
    # ---------------------------------------------------------
    #

    def __repr__(
        self
    ) -> str:

        state = "active" if self._session else "idle"

        return (

            "ConversationManager("

            f"{state}"

            ")"

        )